/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/10.1.31
 * Generated at: 2024-11-06 01:44:01 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.view;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;

public final class order_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports,
                 org.apache.jasper.runtime.JspSourceDirectives {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(3);
    _jspx_dependants.put("/WEB-INF/lib/jakarta.servlet.jsp.jstl-3.0.0.jar", Long.valueOf(1730254531271L));
    _jspx_dependants.put("/WEB-INF/view/menu.jspf", Long.valueOf(1730708760211L));
    _jspx_dependants.put("jar:file:/E:/eclipse/WorkSpace/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/javaweb/WEB-INF/lib/jakarta.servlet.jsp.jstl-3.0.0.jar!/META-INF/c.tld", Long.valueOf(1649407098000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(4);
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public boolean getErrorOnELNotFound() {
    return false;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write(" <!-- 核心庫 -->\r\n");
      out.write("    \r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("	<head>\r\n");
      out.write("		<meta charset=\"UTF-8\">\r\n");
      out.write("		<title>訂購商品</title>\r\n");
      out.write("		<link rel=\"stylesheet\" href=\"https://cdn.jsdelivr.net/npm/purecss@3.0.0/build/pure-min.css\">\r\n");
      out.write("		<link rel=\"stylesheet\" href=\"/javaweb/css/buttons.css\">\r\n");
      out.write("	</head>\r\n");
      out.write("	<body>\r\n");
      out.write("		<!-- menu bar include -->\r\n");
      out.write("		");
      out.write("\r\n");
      out.write("<div class=\"pure-menu pure-menu-horizontal\" style=\"background-color: #dddddd;height: 50px; align-content: center;\">\r\n");
      out.write("	<!-- menu bar -->\r\n");
      out.write("	<a href=\"/javaweb/users\" class=\"pure-menu-heading pure-menu-link\">使用者維護檔</a>\r\n");
      out.write("	<a href=\"/javaweb/login\" class=\"pure-menu-heading pure-menu-link\">登入</a>\r\n");
      out.write("	<a href=\"/javaweb/user/update/password\" class=\"pure-menu-heading pure-menu-link\">修改密碼</a>\r\n");
      out.write("	<a href=\"/javaweb/products\" class=\"pure-menu-heading pure-menu-link\">商品維護檔</a>\r\n");
      out.write("	<a href=\"/javaweb/order\" class=\"pure-menu-heading pure-menu-link\">訂購商品</a>\r\n");
      out.write("	<a href=\"/javaweb/cart\" class=\"pure-menu-heading pure-menu-link\">購物車(結帳, 取消)</a>\r\n");
      out.write("	<a href=\"/javaweb/order/history\" class=\"pure-menu-heading pure-menu-link\">歷史訂單</a>\r\n");
      out.write("	<a href=\"/javaweb/product/sales/ranking\" class=\"pure-menu-heading pure-menu-link\">銷售排行</a>\r\n");
      out.write("	<a href=\"/javaweb/logout\" class=\"pure-menu-heading pure-menu-link\">登出</a>\r\n");
      out.write("</div>");
      out.write("\r\n");
      out.write("		\r\n");
      out.write("		<!-- body content -->\r\n");
      out.write("		<div style=\"padding: 15px\">\r\n");
      out.write("			<form class=\"pure-form\" method=\"post\" action=\"/javaweb/order\">\r\n");
      out.write("				<fieldset>\r\n");
      out.write("					<legend>訂購商品</legend>\r\n");
      out.write("					<table class=\"pure-table\">\r\n");
      out.write("						<thead>\r\n");
      out.write("							<tr>\r\n");
      out.write("								<th>商品 id</th><th>商品名稱</th><th>商品單價</th><th>目前庫存</th><th>下單數量</th>\r\n");
      out.write("							</tr>\r\n");
      out.write("						</thead>\r\n");
      out.write("						<tbody>\r\n");
      out.write("							<tr>\r\n");
      out.write("								<td>\r\n");
      out.write("									1\r\n");
      out.write("									<input type=\"hidden\" name=\"productId\" value=\"1\" >\r\n");
      out.write("								</td>\r\n");
      out.write("								<td>PC</td>\r\n");
      out.write("								<td>\r\n");
      out.write("									30000\r\n");
      out.write("									<input type=\"hidden\" name=\"unitPrice\" value=\"30000\" >\r\n");
      out.write("								</td>\r\n");
      out.write("								<td>50</td>\r\n");
      out.write("								<td><input type=\"number\" name=\"amount\" style=\"width: 100px\" value=\"0\" min=\"0\" max=\"50\"></td>\r\n");
      out.write("							</tr>\r\n");
      out.write("							<tr>\r\n");
      out.write("								<td>\r\n");
      out.write("									2\r\n");
      out.write("									<input type=\"hidden\" name=\"productId\" value=\"2\" >\r\n");
      out.write("								</td>\r\n");
      out.write("								<td>Mobile</td>\r\n");
      out.write("								<td>\r\n");
      out.write("									15000\r\n");
      out.write("									<input type=\"hidden\" name=\"unitPrice\" value=\"15000\" >\r\n");
      out.write("								</td>\r\n");
      out.write("								<td>100</td>\r\n");
      out.write("								<td><input type=\"number\" name=\"amount\" style=\"width: 100px\" value=\"0\" min=\"0\" max=\"100\"></td>\r\n");
      out.write("							</tr>\r\n");
      out.write("							<tr>\r\n");
      out.write("								<td>\r\n");
      out.write("									3\r\n");
      out.write("									<input type=\"hidden\" name=\"productId\" value=\"3\" >\r\n");
      out.write("								</td>\r\n");
      out.write("								<td>MusicBox</td>\r\n");
      out.write("								<td>\r\n");
      out.write("									3000\r\n");
      out.write("									<input type=\"hidden\" name=\"unitPrice\" value=\"3000\" >\r\n");
      out.write("								</td>\r\n");
      out.write("								<td>200</td>\r\n");
      out.write("								<td><input type=\"number\" name=\"amount\" style=\"width: 100px\" value=\"0\" min=\"0\" max=\"200\"></td>\r\n");
      out.write("							</tr>\r\n");
      out.write("							<tr>\r\n");
      out.write("								<td>\r\n");
      out.write("									4\r\n");
      out.write("									<input type=\"hidden\" name=\"productId\" value=\"4\" >\r\n");
      out.write("								</td>\r\n");
      out.write("								<td>Pad</td>\r\n");
      out.write("								<td>\r\n");
      out.write("									20000\r\n");
      out.write("									<input type=\"hidden\" name=\"unitPrice\" value=\"20000\" >\r\n");
      out.write("								</td>\r\n");
      out.write("								<td>75</td>\r\n");
      out.write("								<td><input type=\"number\" name=\"amount\" style=\"width: 100px\" value=\"0\" min=\"0\" max=\"75\"></td>\r\n");
      out.write("							</tr>\r\n");
      out.write("							<tr>\r\n");
      out.write("								<td>\r\n");
      out.write("									5\r\n");
      out.write("									<input type=\"hidden\" name=\"productId\" value=\"5\" >\r\n");
      out.write("								</td>\r\n");
      out.write("								<td>Watch</td>\r\n");
      out.write("								<td>\r\n");
      out.write("									8000\r\n");
      out.write("									<input type=\"hidden\" name=\"unitPrice\" value=\"80000\" >\r\n");
      out.write("								</td>\r\n");
      out.write("								<td>150</td>\r\n");
      out.write("								<td><input type=\"number\" name=\"amount\" style=\"width: 100px\" value=\"0\" min=\"0\" max=\"150\"></td>\r\n");
      out.write("							</tr>\r\n");
      out.write("						</tbody>\r\n");
      out.write("					</table>\r\n");
      out.write("					<p>\r\n");
      out.write("					<button type=\"reset\" class=\"button-warning pure-button\">Reset</button>\r\n");
      out.write("					<button type=\"submit\" class=\"button-success pure-button\">Submit</button>	  \r\n");
      out.write("				</fieldset>\r\n");
      out.write("			</form>\r\n");
      out.write("		</div>\r\n");
      out.write("		<p />\r\n");
      out.write("		\r\n");
      out.write("	</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
